name: Release to Maven Central

on: 
  push:
    tags: 
      - '**'
    branches:
      - none  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 1
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4.6.0
      with:
        distribution: temurin
        java-version: 8
        cache: maven
          
    - name: Release Maven package
      uses: WasiqB/maven-publish-action@v2.9.0
      with:
        gpg_private_key: ${{ secrets.gpg_private_key }}
        gpg_passphrase: ${{ secrets.gpg_passphrase }}
        server_username: ${{ secrets.SONATYPE_USERNAME }}
        server_password: ${{ secrets.SONATYPE_PASSWORD }}
        maven_profiles: release
        settings_path: .mvn/settings.xml 